### ISSUE TITLE
Error when trying to execute python code from client to remote server

### ISSUE THREAD

**Issue by DaveGuenther** [martinohanlon/mcpi#19]
Hi,  

My setup:
SERVER - running a spigot server on a LAN
CLIENT - running Minecraft Java and connecting to SERVER.  Also running python shell for mcpi.  CLIENT and SERVER are not the same computer.

From CLIENT, I can create a Minecraft class instance:
`from mcpi.minecraft import Minecraft
mc=Minecraft.create(<SERVER  IP>,25565)`

However, any command I try to run from the CLIENT hangs for a bit, and then returns the same error below:
```
>>> mc.getPlayerEntityIds()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\lib\site-packages\mcpi\minecraft.py", line 332, in getPlayerEntityIds
    return list(map(int, ids.split("|")))
ValueError: invalid literal for int() with base 10: ''
```

I appreciate any insight you can provide - especially if I'm doing something wrong on my end.

**Comment by DaveGuenther** [comment]
Hi Folks,

Now that I've learned a little more about mcpi I realized that commands sent to the server actually need to travel over port 4711 when the RaspberryJam plugin is running on the server itself.  Modifying my above line of code and changing 25565 to 4711 got me up and running.

Cheers,
Dave
